{
 "title": "Event Sourcing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Producer Event Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evt_src_sys_produce_events_count",
     "legendFormat": "{{env}}:{{uri}}"
    }
   ]
  },
  {
   "title": "Consumer Event Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evt_src_sys_consumer_events_count",
     "legendFormat": "{{env}}:{{uri}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "event_source_consumer_batch_events_count"
    }
   ]
  }
 ]
}